spring:
  application:
    name: bookingapp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/booking_db
    username: root
server: 
  port: 8085